// <auto-generated />
using System;
using HashTag.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HashTag.Migrations
{
    [DbContext(typeof(TrendTagDbContext))]
    [Migration("20251224161057_ExpandedSchemaForSearch")]
    partial class ExpandedSchemaForSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HashTag.Models.CrawlLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HashtagsCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_CrawlLogs_StartedAt");

                    b.HasIndex("SourceId", "Success")
                        .HasDatabaseName("IX_CrawlLogs_SourceId_Success");

                    b.ToTable("CrawlLogs");
                });

            modelBuilder.Entity("HashTag.Models.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LatestPostCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("LatestViewCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TagDisplay")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<int>("TotalAppearances")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Hashtags_CategoryId");

                    b.HasIndex("DifficultyLevel")
                        .HasDatabaseName("IX_Hashtags_DifficultyLevel");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Hashtags_IsActive");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("IX_Hashtags_LastSeen");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("IX_Hashtags_Tag");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("HashTag.Models.HashtagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayNameVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_HashtagCategories_Name");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("HashtagCategories");
                });

            modelBuilder.Entity("HashTag.Models.HashtagHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HashtagId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectedDate")
                        .HasDatabaseName("IX_HashtagHistory_CollectedDate");

                    b.HasIndex("Rank")
                        .HasDatabaseName("IX_HashtagHistory_Rank");

                    b.HasIndex("SourceId");

                    b.HasIndex("HashtagId", "SourceId", "CollectedDate")
                        .HasDatabaseName("IX_HashtagHistory_HashtagId_SourceId_CollectedDate");

                    b.ToTable("HashtagHistory");
                });

            modelBuilder.Entity("HashTag.Models.HashtagKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HashtagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeywordVi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("RelevanceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.5m);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HashtagId");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("IX_HashtagKeywords_Keyword");

                    b.HasIndex("RelevanceScore")
                        .HasDatabaseName("IX_HashtagKeywords_RelevanceScore");

                    b.HasIndex("Keyword", "HashtagId")
                        .HasDatabaseName("IX_HashtagKeywords_Keyword_HashtagId");

                    b.ToTable("HashtagKeywords");
                });

            modelBuilder.Entity("HashTag.Models.HashtagMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DifficultyScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrowthRate30d")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrowthRate7d")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HashtagId")
                        .HasColumnType("int");

                    b.Property<long?>("PostCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("PredictedViewMax")
                        .HasColumnType("bigint");

                    b.Property<long?>("PredictedViewMin")
                        .HasColumnType("bigint");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_HashtagMetrics_Date");

                    b.HasIndex("DifficultyScore")
                        .HasDatabaseName("IX_HashtagMetrics_DifficultyScore");

                    b.HasIndex("HashtagId", "Date")
                        .HasDatabaseName("IX_HashtagMetrics_HashtagId_Date");

                    b.ToTable("HashtagMetrics");
                });

            modelBuilder.Entity("HashTag.Models.HashtagRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoOccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("CorrelationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HashtagId1")
                        .HasColumnType("int");

                    b.Property<int>("HashtagId2")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSeenTogether")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationScore")
                        .HasDatabaseName("IX_HashtagRelations_CorrelationScore");

                    b.HasIndex("HashtagId2");

                    b.HasIndex("HashtagId1", "HashtagId2")
                        .IsUnique()
                        .HasDatabaseName("IX_HashtagRelations_HashtagId1_HashtagId2");

                    b.ToTable("HashtagRelations");
                });

            modelBuilder.Entity("HashTag.Models.HashtagSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastCrawled")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_HashtagSources_Name");

                    b.ToTable("HashtagSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "TikTok",
                            Url = "https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "GoogleTrends",
                            Url = "https://trends.google.com/trends/trendingsearches/daily?geo=VN"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Buffer",
                            Url = "https://buffer.com/resources/tiktok-hashtags/"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Trollishly",
                            Url = "https://www.trollishly.com/tiktok-trending-hashtags/"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "CapCut",
                            Url = "https://www.capcut.com/resource/tiktok-hashtag-guide"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "TokChart",
                            Url = "https://tokchart.com/hashtags"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Countik",
                            Url = "https://countik.com/popular/hashtags"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = false,
                            Name = "Picuki",
                            Url = ""
                        });
                });

            modelBuilder.Entity("HashTag.Models.CrawlLog", b =>
                {
                    b.HasOne("HashTag.Models.HashtagSource", "Source")
                        .WithMany("CrawlLogs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HashTag.Models.Hashtag", b =>
                {
                    b.HasOne("HashTag.Models.HashtagCategory", "Category")
                        .WithMany("Hashtags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HashTag.Models.HashtagCategory", b =>
                {
                    b.HasOne("HashTag.Models.HashtagCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("HashTag.Models.HashtagHistory", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag")
                        .WithMany("History")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HashTag.Models.HashtagSource", "Source")
                        .WithMany("History")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hashtag");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HashTag.Models.HashtagKeyword", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag")
                        .WithMany("Keywords")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("HashTag.Models.HashtagMetrics", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag")
                        .WithMany("Metrics")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("HashTag.Models.HashtagRelation", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag1")
                        .WithMany("RelationsAsHashtag1")
                        .HasForeignKey("HashtagId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HashTag.Models.Hashtag", "Hashtag2")
                        .WithMany("RelationsAsHashtag2")
                        .HasForeignKey("HashtagId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hashtag1");

                    b.Navigation("Hashtag2");
                });

            modelBuilder.Entity("HashTag.Models.Hashtag", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Keywords");

                    b.Navigation("Metrics");

                    b.Navigation("RelationsAsHashtag1");

                    b.Navigation("RelationsAsHashtag2");
                });

            modelBuilder.Entity("HashTag.Models.HashtagCategory", b =>
                {
                    b.Navigation("Hashtags");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("HashTag.Models.HashtagSource", b =>
                {
                    b.Navigation("CrawlLogs");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
