// <auto-generated />
using System;
using HashTag.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HashTag.Migrations
{
    [DbContext(typeof(TrendTagDbContext))]
    [Migration("20260201114622_MultiLanguageAndRegionSupport")]
    partial class MultiLanguageAndRegionSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HashTag.Models.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayNameVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories");
                });

            modelBuilder.Entity("HashTag.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExcerptEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeaturedImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaDescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaKeywordsEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MetaTitleEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SlugEn")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("HashTag.Models.BlogPostTag", b =>
                {
                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<int>("BlogTagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BlogPostId", "BlogTagId");

                    b.HasIndex("BlogTagId");

                    b.ToTable("BlogPostTags");
                });

            modelBuilder.Entity("HashTag.Models.BlogTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("BlogTags");
                });

            modelBuilder.Entity("HashTag.Models.CrawlLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HashtagsCollected")
                        .HasColumnType("int");

                    b.Property<string>("LogMessages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SourceId", "Success" }, "IX_CrawlLogs_SourceId_Success");

                    b.HasIndex(new[] { "StartedAt" }, "IX_CrawlLogs_StartedAt");

                    b.ToTable("CrawlLogs");
                });

            modelBuilder.Entity("HashTag.Models.GenerationHashtagSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.Property<int?>("HashtagId")
                        .HasColumnType("int");

                    b.Property<string>("HashtagText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("PerformanceViews")
                        .HasColumnType("bigint");

                    b.Property<bool>("WasSelected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("HashtagId");

                    b.ToTable("GenerationHashtagSelections");
                });

            modelBuilder.Entity("HashTag.Models.GenerationRateLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenerationCount")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WindowStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GenerationRateLimits");
                });

            modelBuilder.Entity("HashTag.Models.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("VN");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LatestPostCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("LatestViewCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TagDisplay")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<int>("TotalAppearances")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Hashtags_CategoryId");

                    b.HasIndex(new[] { "CountryCode" }, "IX_Hashtags_CountryCode");

                    b.HasIndex(new[] { "DifficultyLevel" }, "IX_Hashtags_DifficultyLevel");

                    b.HasIndex(new[] { "IsActive" }, "IX_Hashtags_IsActive");

                    b.HasIndex(new[] { "LastSeen" }, "IX_Hashtags_LastSeen");

                    b.HasIndex(new[] { "Tag", "CountryCode" }, "IX_Hashtags_Tag_CountryCode")
                        .IsUnique();

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("HashTag.Models.HashtagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayNameVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_HashtagCategories_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "ParentCategoryId" }, "IX_HashtagCategories_ParentCategoryId");

                    b.ToTable("HashtagCategories");
                });

            modelBuilder.Entity("HashTag.Models.HashtagGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CachedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenerationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InputDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InputDescriptionHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecommendedHashtags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<string>("UserFeedback")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WasCopied")
                        .HasColumnType("bit");

                    b.Property<bool>("WasSaved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HashtagGenerations");
                });

            modelBuilder.Entity("HashTag.Models.HashtagHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CollectedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("FeaturedCreatorsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HashtagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsViral")
                        .HasColumnType("bit");

                    b.Property<long?>("PostCount")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("RankChange")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RankDiff")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("TrendDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TrendMomentum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TrendScore")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Category" }, "IX_HashtagHistory_Category");

                    b.HasIndex(new[] { "CollectedDate" }, "IX_HashtagHistory_CollectedDate");

                    b.HasIndex(new[] { "HashtagId", "SourceId", "CollectedDate" }, "IX_HashtagHistory_HashtagId_SourceId_CollectedDate");

                    b.HasIndex(new[] { "Rank" }, "IX_HashtagHistory_Rank");

                    b.HasIndex(new[] { "SourceId" }, "IX_HashtagHistory_SourceId");

                    b.HasIndex(new[] { "ViewCount" }, "IX_HashtagHistory_ViewCount");

                    b.ToTable("HashtagHistory", (string)null);
                });

            modelBuilder.Entity("HashTag.Models.HashtagKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("HashtagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeywordVi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("RelevanceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0.5m);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HashtagId" }, "IX_HashtagKeywords_HashtagId");

                    b.HasIndex(new[] { "Keyword" }, "IX_HashtagKeywords_Keyword");

                    b.HasIndex(new[] { "Keyword", "HashtagId" }, "IX_HashtagKeywords_Keyword_HashtagId");

                    b.HasIndex(new[] { "RelevanceScore" }, "IX_HashtagKeywords_RelevanceScore");

                    b.ToTable("HashtagKeywords");
                });

            modelBuilder.Entity("HashTag.Models.HashtagMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DifficultyScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GrowthRate30d")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GrowthRate7d")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("HashtagId")
                        .HasColumnType("int");

                    b.Property<long?>("PostCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("PredictedViewMax")
                        .HasColumnType("bigint");

                    b.Property<long?>("PredictedViewMin")
                        .HasColumnType("bigint");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Date" }, "IX_HashtagMetrics_Date");

                    b.HasIndex(new[] { "DifficultyScore" }, "IX_HashtagMetrics_DifficultyScore");

                    b.HasIndex(new[] { "HashtagId", "Date" }, "IX_HashtagMetrics_HashtagId_Date");

                    b.ToTable("HashtagMetrics");
                });

            modelBuilder.Entity("HashTag.Models.HashtagRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoOccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("CorrelationScore")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("HashtagId1")
                        .HasColumnType("int");

                    b.Property<int>("HashtagId2")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSeenTogether")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationScore" }, "IX_HashtagRelations_CorrelationScore");

                    b.HasIndex(new[] { "HashtagId1", "HashtagId2" }, "IX_HashtagRelations_HashtagId1_HashtagId2")
                        .IsUnique();

                    b.HasIndex(new[] { "HashtagId2" }, "IX_HashtagRelations_HashtagId2");

                    b.ToTable("HashtagRelations");
                });

            modelBuilder.Entity("HashTag.Models.HashtagSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastCrawled")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_HashtagSources_Name")
                        .IsUnique();

                    b.ToTable("HashtagSources");
                });

            modelBuilder.Entity("HashTag.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ServiceName" }, "IX_SystemLogs_ServiceName");

                    b.HasIndex(new[] { "Timestamp" }, "IX_SystemLogs_Timestamp");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("HashTag.Models.BlogPost", b =>
                {
                    b.HasOne("HashTag.Models.BlogCategory", "Category")
                        .WithMany("BlogPosts")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HashTag.Models.BlogPostTag", b =>
                {
                    b.HasOne("HashTag.Models.BlogPost", "BlogPost")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HashTag.Models.BlogTag", "BlogTag")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("BlogTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("BlogTag");
                });

            modelBuilder.Entity("HashTag.Models.CrawlLog", b =>
                {
                    b.HasOne("HashTag.Models.HashtagSource", "Source")
                        .WithMany("CrawlLogs")
                        .HasForeignKey("SourceId")
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HashTag.Models.GenerationHashtagSelection", b =>
                {
                    b.HasOne("HashTag.Models.HashtagGeneration", "Generation")
                        .WithMany("SelectedHashtags")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HashTag.Models.Hashtag", "Hashtag")
                        .WithMany()
                        .HasForeignKey("HashtagId");

                    b.Navigation("Generation");

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("HashTag.Models.Hashtag", b =>
                {
                    b.HasOne("HashTag.Models.HashtagCategory", "Category")
                        .WithMany("Hashtags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HashTag.Models.HashtagCategory", b =>
                {
                    b.HasOne("HashTag.Models.HashtagCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("HashTag.Models.HashtagHistory", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag")
                        .WithMany("History")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HashTag.Models.HashtagSource", "Source")
                        .WithMany("History")
                        .HasForeignKey("SourceId")
                        .IsRequired();

                    b.Navigation("Hashtag");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HashTag.Models.HashtagKeyword", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag")
                        .WithMany("Keywords")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("HashTag.Models.HashtagMetrics", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag")
                        .WithMany("Metrics")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("HashTag.Models.HashtagRelation", b =>
                {
                    b.HasOne("HashTag.Models.Hashtag", "Hashtag1")
                        .WithMany("RelationsAsHashtag1")
                        .HasForeignKey("HashtagId1")
                        .IsRequired();

                    b.HasOne("HashTag.Models.Hashtag", "Hashtag2")
                        .WithMany("RelationsAsHashtag2")
                        .HasForeignKey("HashtagId2")
                        .IsRequired();

                    b.Navigation("Hashtag1");

                    b.Navigation("Hashtag2");
                });

            modelBuilder.Entity("HashTag.Models.BlogCategory", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("HashTag.Models.BlogPost", b =>
                {
                    b.Navigation("BlogPostTags");
                });

            modelBuilder.Entity("HashTag.Models.BlogTag", b =>
                {
                    b.Navigation("BlogPostTags");
                });

            modelBuilder.Entity("HashTag.Models.Hashtag", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Keywords");

                    b.Navigation("Metrics");

                    b.Navigation("RelationsAsHashtag1");

                    b.Navigation("RelationsAsHashtag2");
                });

            modelBuilder.Entity("HashTag.Models.HashtagCategory", b =>
                {
                    b.Navigation("Hashtags");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("HashTag.Models.HashtagGeneration", b =>
                {
                    b.Navigation("SelectedHashtags");
                });

            modelBuilder.Entity("HashTag.Models.HashtagSource", b =>
                {
                    b.Navigation("CrawlLogs");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
